# Create Mentors
# e.g. Mentor.create(name: "Dammy", image: "http://...")
# e.g. Mentor.create(name: "Dammy") => image is ."/assets/images/user-solid.svg"
Mentor.create(name: "John")
Mentor.create(name: "John")
Mentor.create(name: "John")
Mentor.create(name: "John")
Mentor.create(name: "John")
Mentor.create(name: "John")
Mentor.create(name: "John")
Mentor.create(name: "John")
Mentor.create(name: "John")
Mentor.create(name: "John")
Mentor.create(name: "John")
Mentor.create(name: "John")
Mentor.create(name: "John")
Mentor.create(name: "John")
Mentor.create(name: "John")
Mentor.create(name: "John")
Mentor.create(name: "John")
Mentor.create(name: "John")
Mentor.create(name: "John")
Mentor.create(name: "John")